'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("XINFO.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to XINFO - Xstrahl Helpful Information and Needful Tools.
        '''</summary>
        Public ReadOnly Property XINFO_Main_000() As String
            Get
                Return ResourceManager.GetString("XINFO_Main_000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error Codes.
        '''</summary>
        Public ReadOnly Property XINFO_Main_001() As String
            Get
                Return ResourceManager.GetString("XINFO_Main_001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manuals.
        '''</summary>
        Public ReadOnly Property XINFO_Main_002() As String
            Get
                Return ResourceManager.GetString("XINFO_Main_002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Public ReadOnly Property XINFO_Main_003() As String
            Get
                Return ResourceManager.GetString("XINFO_Main_003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imperium.
        '''</summary>
        Public ReadOnly Property XINFO_Main_004() As String
            Get
                Return ResourceManager.GetString("XINFO_Main_004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to XLoop is running and cannot be started a 2nd time. You should see the icon in the task bar (usually at the bottom of the screen)..
        '''</summary>
        Public ReadOnly Property XINFO_Main_005() As String
            Get
                Return ResourceManager.GetString("XINFO_Main_005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to XLoop already running.
        '''</summary>
        Public ReadOnly Property XINFO_Main_006() As String
            Get
                Return ResourceManager.GetString("XINFO_Main_006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print.
        '''</summary>
        Public ReadOnly Property XINFO_Style_DocViewer_001() As String
            Get
                Return ResourceManager.GetString("XINFO_Style_DocViewer_001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy.
        '''</summary>
        Public ReadOnly Property XINFO_Style_DocViewer_002() As String
            Get
                Return ResourceManager.GetString("XINFO_Style_DocViewer_002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zoom IN.
        '''</summary>
        Public ReadOnly Property XINFO_Style_DocViewer_003() As String
            Get
                Return ResourceManager.GetString("XINFO_Style_DocViewer_003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zoom OUT.
        '''</summary>
        Public ReadOnly Property XINFO_Style_DocViewer_004() As String
            Get
                Return ResourceManager.GetString("XINFO_Style_DocViewer_004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Actual Size.
        '''</summary>
        Public ReadOnly Property XINFO_Style_DocViewer_005() As String
            Get
                Return ResourceManager.GetString("XINFO_Style_DocViewer_005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fit to Width.
        '''</summary>
        Public ReadOnly Property XINFO_Style_DocViewer_006() As String
            Get
                Return ResourceManager.GetString("XINFO_Style_DocViewer_006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to whole page.
        '''</summary>
        Public ReadOnly Property XINFO_Style_DocViewer_007() As String
            Get
                Return ResourceManager.GetString("XINFO_Style_DocViewer_007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Two Pages.
        '''</summary>
        Public ReadOnly Property XINFO_Style_DocViewer_008() As String
            Get
                Return ResourceManager.GetString("XINFO_Style_DocViewer_008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Public ReadOnly Property XINFO_UC01_001() As String
            Get
                Return ResourceManager.GetString("XINFO_UC01_001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error Code.
        '''</summary>
        Public ReadOnly Property XINFO_UC01_002() As String
            Get
                Return ResourceManager.GetString("XINFO_UC01_002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Message displayed.
        '''</summary>
        Public ReadOnly Property XINFO_UC01_003() As String
            Get
                Return ResourceManager.GetString("XINFO_UC01_003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Public ReadOnly Property XINFO_UC01_004() As String
            Get
                Return ResourceManager.GetString("XINFO_UC01_004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Xstrahl &quot;classic&quot; Database Browser.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_001() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to treatments found in DB.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_002() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply Filter.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_003() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to first item.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_004() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to previous item.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_005() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to next item.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_006() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to last item.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_007() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to of.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_008() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter any text to filter the database. Enter a date as yyyymmdd. You cannot search for treatment time..
        '''</summary>
        Public ReadOnly Property XINFO_UC03_009() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter your filter information.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_010() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find Database.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_011() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export as CSV.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_012() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export as XML.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_013() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export as XPS.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_014() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot; &quot;.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_015() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to contains.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_016() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_016", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to starts with.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_017() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_017", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to exact match.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_018() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_018", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to group by.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_019() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_019", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_020() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_020", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_021() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_021", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Summary Report.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_022() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_022", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Read me first.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_023() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_023", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The records, based on the current filter, have been exported..
        '''</summary>
        Public ReadOnly Property XINFO_UC03_024() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_024", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export Information.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_025() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_025", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select and confirm the Imperium Folder with D3KTMNT.DBF.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_050() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_050", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to show Treatment Protocol.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_051() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_051", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The folder you have selected doesn&apos;t contain {0}.~Please select a valid folder. By default {1} will be used..
        '''</summary>
        Public ReadOnly Property XINFO_UC03_052() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_052", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File not found.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_053() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_053", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exporting database records as individual XPS document requires some time.~{0} items can be exported in about {1} seconds.~The real time depends on system performance.~~Do you want to continue?.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_054() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_054", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The licence file for hospital code {0} could not be found.~Please get a valid licence and copy the file unchanged to {1}..
        '''</summary>
        Public ReadOnly Property XINFO_UC03_056() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_056", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Licence Information.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_057() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_057", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to More than one licence file found for this option.~Please get a valid licence for hospital code {0} and copy the file unchanged to {1}.~Delete all backup copies or invalid licence files..
        '''</summary>
        Public ReadOnly Property XINFO_UC03_058() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_058", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The licence has been found as NOT VALID!~~Error-Code: {0}~~Active? {1}~Can expire? {2}~Creation Date: {3}~Serial Number: {4}~Expire Date: {5}~Filename: {6}~Licence Key: {7}~Licence Type: {8}.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_059() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_059", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The licence itself is valid, but it was made for a different serial number (hospital code).~Your serial number (hospital code) is {0}..
        '''</summary>
        Public ReadOnly Property XINFO_UC03_060() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_060", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The licence itself is valid, but it was made for a different product..
        '''</summary>
        Public ReadOnly Property XINFO_UC03_061() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_061", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The licence itself is valid, but it was made with the status &quot;inactive&quot;..
        '''</summary>
        Public ReadOnly Property XINFO_UC03_062() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_062", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export Information.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_063() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_063", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Licence validation error: {0}.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_064() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_064", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database Index.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_100() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patient (Full Name).
        '''</summary>
        Public ReadOnly Property XINFO_UC03_101() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patient ID.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_102() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patient Date of Birth.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_103() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patient Picture (Filename).
        '''</summary>
        Public ReadOnly Property XINFO_UC03_104() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Treatment Field 1.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_104_TRT() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_104_TRT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clinician.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_105() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Treatment Field.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_106() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_106", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Treatment Field 2.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_106_TRT() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_106_TRT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Treatment Position.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_107() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_107", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter Code.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_108() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_108", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Applicator Code.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_109() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_109", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Treatment Date.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_110() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_110", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Treatment Time.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_111() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_111", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter kV.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_112() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_112", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter mA.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_113() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_113", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter HVL.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_114() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_114", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Applicator Data.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_115() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_115", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dose Admin.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_116() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_116", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time Admin.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_117() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_117", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Operator.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_118() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_118", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dose Set.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_119() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_119", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time Set.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_120() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_120", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error Codes.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_121() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_121", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backgroundjob Information.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_200() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backgroundjob was cancelled by unknown reason..
        '''</summary>
        Public ReadOnly Property XINFO_UC03_201() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backgroundjob had an error. Please repeat the export..
        '''</summary>
        Public ReadOnly Property XINFO_UC03_202() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export of XPS documents was cancelled by the user..
        '''</summary>
        Public ReadOnly Property XINFO_UC03_203() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_203", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export of XPS documents finished successfully..
        '''</summary>
        Public ReadOnly Property XINFO_UC03_204() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_204", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backgroundjob finished, but it can be that not all database records were exported..
        '''</summary>
        Public ReadOnly Property XINFO_UC03_205() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_205", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Something is going while creating/saving XPS documents:~{0}.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_206() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_206", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Problem while generating/saving XPS document.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_207() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_207", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IMPERIUM Treatment Record.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_300() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page.
        '''</summary>
        Public ReadOnly Property XINFO_UC03_301() As String
            Get
                Return ResourceManager.GetString("XINFO_UC03_301", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EXPORTING XPS DOCUMENTS.
        '''</summary>
        Public ReadOnly Property XINFO_UC99_001() As String
            Get
                Return ResourceManager.GetString("XINFO_UC99_001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exporting plan {0} of {1}.~{2} plans per sec., export finished approx. at {3}..
        '''</summary>
        Public ReadOnly Property XINFO_UC99_002() As String
            Get
                Return ResourceManager.GetString("XINFO_UC99_002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check me to stop export..
        '''</summary>
        Public ReadOnly Property XINFO_UC99_003() As String
            Get
                Return ResourceManager.GetString("XINFO_UC99_003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property xstrahl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xstrahl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to vgaxwi4pbatrvejmumTLQf4Zi2sTjsW5WDteFK1ea8ssx7lWEvBaKA6pbSncKBvede4iM9U2eChENito1WvZK95quxfj2YfjUycXESvCgYnjwF0nB2NE7RMwvOXWwx5AnwnE5S5NFBmfODohVK9P7Xmn24mPxqRGJ0wBcrZY055XagnKpXBE+5mEgpqVk6hg+PjB2trm2xItySkzDHisnGBcCQNZZi9ytd1mPAdpfDaBM/RfqK5uRMvYC71Fb8TIpUWxkDbJ9DOnESQFbNti5kZK4+5rm96AuzU2AHbcruC8i83VP49SVM16D9tU1R8fjK9sQF9WoujmtSKKd/h9m8Rt7bRTt795azmL6prspwTivjLjJ/pyHiy7reYoky/egQyb8sW+UyQ6VtqE1lKJeigBlYuGh9d+3mXNxQ2g8IaQmQXpuRSJj0R9OJFLGASxx4H1a7RuYeMJhcg1ugp8glUvaSSaP6vNJkUyXIYh6nvekqpMDNBj+e/rmnh4O2FJ [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property Xstrahl_RSAFullKey() As String
            Get
                Return ResourceManager.GetString("Xstrahl_RSAFullKey", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
